services:
  saludlink_db:
    image: postgres:15-alpine
    container_name: saludlink_db
    environment:
      POSTGRES_DB: saludlink_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: saludlink_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@saludlink.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8082:80"
    depends_on:
      - saludlink_db

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - saludlink_db
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: saludlink_db
      DB_PORT: "5432"
      DB_NAME: saludlink_db
      DB_USERNAME: postgres
      DB_PASSWORD: admin123
      JWT_SECRET: local-docker-jwt-secret-min-32-characters-long
      CORS_ALLOWED_ORIGINS: http://localhost:4200,http://localhost:5173

volumes:
  postgres_data:
